# Model arguments
model_name_or_path: /home/chang/llm/TempModels/google-gemma-2-9b-it-saju/2-step-250214-release/2a-saju-instruct-all-attn/checkpoint-final-250214-release
model_revision: main
torch_dtype: bfloat16
attn_implementation: eager

# Data training arguments
dataset_name: AI-MO/NuminaMath-TIR
dataset_configs:
- all

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.55
do_eval: false
eval_strategy: steps
eval_steps: 1000000
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: google-gemma-2-9b-it-saju
hub_strategy: every_save
push_to_hub: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 2
num_train_epochs: 1
output_dir: /home/chang/llm/TempModels/google-gemma-2-9b-it-saju/NuminaMath-TIR-grpo
run_name: gemma-2-9b-it-saju-NuminaMath-TIR-grpo
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
